services:
  monitoring-provider-loki:
    build:
      context: ./loki
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_LOKI_IMAGE_VERSION}
    env_file:
      - ./loki/.env
    volumes:
      - ./loki/.data:/loki
    command: "-config.file=/etc/loki/local-config.yaml"
  
  monitoring-provider-alloy:
    build:
      context: ./alloy
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_ALLOY_IMAGE_VERSION}
    env_file:
      - ./alloy/.env
    volumes:
      - ./alloy/.data:/var/lib/alloy/data
      - ./alloy/config.alloy:/etc/alloy/config.alloy
      - ./alloy/app-logs/:/var/log/ # Adjust the path as needed for your application logs
    command: [ "run", "/etc/alloy/config.alloy", "--storage.path=/var/lib/alloy/data", "--server.http.listen-addr=0.0.0.0:12345" ]

  monitoring-provider-grafana:
    build:
      context: ./grafana
      args:
        - PROVIDER_VERSION=${MONITORING_PROVIDER_GRAFANA_IMAGE_VERSION}
    env_file:
      - ./grafana/.env
    volumes:
      - ./grafana/.data:/var/lib/grafana
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - monitoring-provider-loki
      - monitoring-provider-alloy
