services:
  email_provider:
    ports:
      - '1025:1025'
    command:
      - --log-mail-contents

  oauth_provider:
    environment:
      KC_HTTP_MANAGEMENT_PORT: 9000
      KC_HTTP_MANAGEMENT_RELATIVE_PATH: '/'
    ports:
      - '9000:9000'
    command:
      - start-dev
      - --import-realm

  sqldb_provider:
    ports:
      - '5432:5432'

  aws_services_provider:
    ports:
      - '127.0.0.1:4566:4566'