services:
  email-provider:
    build:
      context: ./email-provider
      args:
        - PROVIDER_VERSION=${EMAIL_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./email-provider/.env

  oauth-provider:
    build:
      context: ./oauth-provider
      args:
        - PROVIDER_VERSION=${OAUTH_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./oauth-provider/.env
    volumes:
      - ./oauth-provider/providers:/opt/keycloak/providers
      - ./oauth-provider/helms:/opt/keycloak/data/import
      - ./.provider-logs/oauth-provider:/opt/keycloak/data/log
    healthcheck:
      test: [ "CMD-SHELL", "/opt/keycloak/bin/static-curl -f localhost" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      sqldb-provider:
        condition: service_healthy

  sqldb-provider:
    build:
      context: ./sqldb-provider
      args:
        - PROVIDER_VERSION=${SQLDB_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./sqldb-provider/.env
    volumes:
      - ./sqldb-provider/.data:/var/lib/postgresql/data
      - ./sqldb-provider/psql.conf:/etc/psql.conf
      - ./.provider-logs/sqldb-provider:/var/log/postgresql
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}' ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: postgres -c config_file=/etc/psql.conf

  aws-services-provider:
    build:
      context: ./aws-services-provider
      args:
        - PROVIDER_VERSION=${AWS_SERVICES_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./aws-services-provider/.env
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./aws-services-provider/ready.d/:/etc/localstack/init/ready.d/

  mongodb-provider:
    build:
      context: ./mongodb-provider
      args:
        - PROVIDER_VERSION=${MONGODB_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./mongodb-provider/.env
    volumes:
      - ./mongodb-provider/.data/db:/data/db
    healthcheck:
      test: >
        mongosh --quiet --username $$MONGO_INITDB_ROOT_USERNAME
        --password $$MONGO_INITDB_ROOT_PASSWORD
        --authenticationDatabase admin
        --eval 'db.runCommand({ping:1}).ok'
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    depends_on:
      sqldb-provider:
        condition: service_healthy

  feature-flag-provider:
    build:
      context: ./feature-flag-provider
      args:
        - PROVIDER_VERSION=${FEATURE_FLAG_PROVIDER_IMAGE_VERSION}
    env_file:
      - ./feature-flag-provider/.env
    volumes:
      - ./feature-flag-provider/.data/uploads:/usr/local/src/app/packages/back-end/uploads

include:
  - path: ./monitoring-provider/compose.yml
