services:
  email-provider:
    ports:
      - '1025:1025'
    command:
      - --log-mail-contents

  oauth-provider:
    environment:
      KC_HTTP_MANAGEMENT_PORT: 9001
      KC_HTTP_MANAGEMENT_RELATIVE_PATH: '/'
    ports:
      - '8180:8180'
      - '9001:9001'
    command:
      - start-dev
      - --import-realm
      # - start
      # - --import-realm
      # - --hostname=witty-alpaca-current.ngrok-free.app
      # - --proxy-headers=xforwarded
      # - --http-enabled=true

  sqldb-provider:
    ports:
      - '5432:5432'

  aws-services-provider:
    ports:
      - '127.0.0.1:4566:4566'
  
  mongodb-provider:
    ports:
      - '27017:27017'
  
  feature-flag-provider:
    ports:
      - '3000:3000'
      - '3100:3100'

  sqldbmngr_provider:
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    image: adminer
    ports:
      - '5433:8080'

  monitoring-provider-loki:
    ports:
      - '3100:3100'

  monitoring-provider-grafana:
    ports:
      - '3000:3000'