services:
  email-provider:
    labels:
      project: lit-4d
    ports:
      - '1080:1080'
      - '1025:1025'
    command:
      - --log-mail-contents

  oauth-provider:
    labels:
      project: lit-4d
    ports:
      - '8180:8180'
      - '9101:9101'
    healthcheck:
      test: [ "CMD-SHELL", "/opt/keycloak/bin/static-curl -f localhost:9101/health/ready" ]
    command:
      - start-dev
      - --import-realm
      # - start
      # - --optimized

  sqldb-provider:
    labels:
      project: lit-4d
    ports:
      - '5432:5432'

  aws-services-provider:
    labels:
      project: lit-4d
    ports:
      - '127.0.0.1:4566:4566'
  
  mongodb-provider:
    labels:
      project: lit-4d
    ports:
      - '27017:27017'
  
  feature-flag-provider:
    labels:
      project: lit-4d
    ports:
      - '3000:3000'
      - '3100:3100'

  sqldbmngr_provider:
    labels:
      project: lit-4d
    environment:
      - ADMINER_DESIGN=pepa-linha-dark
    image: adminer
    ports:
      - '5433:8080'

include:
  - path: ./monitoring-provider/compose.override.yml